#!/bin/bash
# Place this file in `.git/hooks/`
xcodegen
git add Paywall.xcodeproj
sed -i '' "4s/.*/    s.version      = \"$(sed -n 21p ./Sources/Paywall/Misc/Constants.swift)\"/" Paywall.podspec
git add Paywall.podspec