#!/bin/bash
# Place this file in `.git/hooks/`
xcodegen
git add Superwall.xcodeproj
sed -i '' "4s/.*/    s.version      = \"$(sed -n 21p ./Sources/Superwall/Misc/Constants.swift)\"/" Superwall.podspec
git add Superwall.podspec
