name: Emerge Tools Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    env:
      PRODUCT_NAME: SuperwallKit
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: xcodegen
        uses: xavierLowmiller/xcodegen-action@1.1.2

      - name: Build XCFramework
        run: sh make-xcframework.sh $PRODUCT_NAME

      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.1.0
        with:
          build_type: release
          artifact_path: ./${{ env.PRODUCT_NAME }}.xcframework.zip
          emerge_api_key: ${{ secrets.EMERGE_API_KEY }}
