name: Run Tests

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'project.yml'
      - '**/*.swift'
      - '!Examples/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: xcodegen
        uses: xavierLowmiller/xcodegen-action@1.2.3
      - name: Run Tests
        run: |
          xcodebuild -project SuperwallKit.xcodeproj -scheme SuperwallKit -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15 Pro' test
